=== ziaUbi/software-engineering-cyberbullying-detection-system-/ingestion_system/Ingestion_Configuration_schema/IngestionSystemConfigurationSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "maxNumMissingSamples": {
      "type": "integer",
      "minimum": 0
    },
    "current_phase": {
      "type": "string",
      "enum": ["development", "production", "evaluation"]
    },
    "service": {
      "type": "boolean"
    },
    "production_sessions": {
      "type": "integer",
      "minimum": 0
    },
    "development_sessions": {
      "type": "integer",
      "minimum": 0
    },
    "evaluation_sessions": {
      "type": "integer",
      "minimum": 0
    },
    "ip_preparation": {
      "type": "string",
      "format": "ipv4"
    },
    "ip_evaluation": {
      "type": "string",
      "format": "ipv4"
    },
    "port_preparation": {
      "type": "integer",
      "minimum": 1,
      "maximum": 65535
    },
    "port_evaluation": {
      "type": "integer",
      "minimum": 1,
      "maximum": 65535
    },
    "ip_ingestion": {
      "type": "string",
      "format": "ipv4"
    },
    "port_ingestion": {
      "type": "integer",
      "minimum": 1,
      "maximum": 65535
    }
  },
  "required": [
    "maxNumMissingSamples",
    "current_phase",
    "service",
    "production_sessions",
    "development_sessions",
    "evaluation_sessions",
    "ip_preparation",
    "ip_evaluation",
    "port_preparation",
    "port_evaluation",
    "ip_ingestion",
    "port_ingestion"
  ]
}

=== ziaUbi/software-engineering-cyberbullying-detection-system-/ingestion_system/Ingestion_Configuration_schema/IngestionSystemConfiguration.json
{
    "maxNumMissingSamples": 3,
    "current_phase": "production",
    "service": true,
    "production_sessions": 5000,
    "development_sessions": 500,
    "evaluation_sessions": 50,
    "ip_preparation": "127.0.0.1",
    "ip_evaluation": "172.20.10.2",
    "port_preparation": 5002,
    "port_evaluation": 5210,
    "ip_ingestion": "0.0.0.0",
    "port_ingestion": 5001
}
